### ISSUE TITLE
Test if stackable agents are running

### ISSUE THREAD

**Issue by backstreetkiwi** [stackabletech/pit#2]

**Comment by soenkeliebau** [comment]
If it helps, the agent also opens a local port (3000 by default) that could be checked. 
But looking at the `node` object in Kubernetes is much more complete of course.

**Comment by backstreetkiwi** [comment]
> If it helps, the agent also opens a local port (3000 by default) that could be checked.
> But looking at the `node` object in Kubernetes is much more complete of course.

Yep, thanks. 'agent' in this case means 'stackable cluster'. Later, we should be able to do specific tests anyway...

**Comment by backstreetkiwi** [comment]
grep the result of "kubectl get nodes" for "worker-2", which is better than before but falls short of being "complete" ;-) 
=> "best effort" as of now
